name: Github Actions Test

on: [ push, pull_request ]

jobs:

  helloci-build:
    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: helloci

      strategy:
        matrix:
          go_version: [ 1.21 ]
          os: [ ubuntu-latest ]

          steps:

            - name: Set up Go ${{ matrix.go_version }}
              uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go_version }}
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v4

            - name: Tidy
              run: |
                go mod tidy

            - name: Build
              run: |
                go build -v -o helloci .

            - name: Collect main.go file
              uses: actions/upload-artifact@v4.2.0
              with:
                name: main-output
                path: main.go

            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                name: ccr.ccs.tencentyun.com/yaiyo/helloci:beta
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                registry: ccr.ccs.tencentyun.com
                dockerfile: Dockerfile
                tag_names: true